### ISSUE TITLE
This repository now supports two datasets: cityscapes and camvid, cityscapes is not included

### ISSUE THREAD

**Issue by Linda-L** [xiaoyufenfei/Efficient-Segmentation-Networks#18]
/home/ll/anaconda3/envs/t1.2/bin/python /media/ll/L/Efficient-Segmentation-Networks/train.py
1.2
=====> input size:(512, 1024)
Namespace(batch_size=4, classes=19, cuda=True, dataset='cityscapes', gpus='0', input_size='512,1024', logFile='log.txt', lr=0.0005, lr_schedule='warmpoly', max_epochs=10, model='FastSCNN', num_cycles=1, num_workers=4, optim='adam', poly_exp=0.9, random_mirror=True, random_scale=True, resume='', savedir='./checkpoint/', train_type='trainval', use_focal=False, use_label_smoothing=False, use_lovaszsoftmax=False, use_ohem=False, warmup_factor=0.3333333333333333, warmup_iters=500)
=====> use gpu id: '0'
=====> set Global Seed:  1234
=====> building network
=====> computing network parameters and FLOPs
the number of parameters: 1138051 ==> 1.14 M
find file:  ./dataset/inform/cityscapes_inform.pkl
length of dataset:  122
length of dataset:  59
=====> Dataset statistics
data['classWeights']:  [ 1.4705521  9.505282  10.492059  10.492059  10.492059  10.492059
 10.492059  10.492059  10.492059  10.492059  10.492059  10.492059
 10.492059  10.492059  10.492059  10.492059  10.492059  10.492059
  5.131664 ]
mean and std:  [72.3924   82.90902  73.158325] [45.319206 46.15292  44.91484 ]
Traceback (most recent call last):
  File "/media/ll/L/Efficient-Segmentation-Networks/train.py", line 401, in <module>
    train_model(args)
  File "/media/ll/L/Efficient-Segmentation-Networks/train.py", line 145, in train_model
    "This repository now supports two datasets: cityscapes and camvid, %s is not included" % args.dataset)
NotImplementedError: This repository now supports two datasets: cityscapes and camvid, cityscapes is not included

Process finished with exit code 1

**Comment by adamsigal** [comment]
Did you figure out a way to get this to work?

**Comment by chinnl** [comment]
Hi, We need to pass --use_focal, --use_ohem or --use_lovaszsoftmax to train with cityscapes dataset.
